export const COLORS = {
  TITLE_HEAD: '#333333',
  TEXT: '#2D2D2D',
  BACKGROUND: '#FFFFFF',
  BACKGROUND_GRAY: '#EAEDED',
  LINE_BORDER: '#282626',

  ORANGE: '#F2994A',
  ORANGE_LIGHT: '#F1A10A',

  GRAY: '#BDBDBD',
  GRAY_LIGHT: '#E0E0E0',
} as const